summarize_podcast_task:
  description: >
    Transcribe the podcast from the given URL and summarize the key points.
  expected_output: >
    A comprehensive and clear summary of the youtube podcast. You should summarize the transcript into main keypoints.

send_message_to_slack_task:
  description: >
    Send the summary to slack.
  expected_output: >
    A confirmation that message has been sent to slack channel.

write_summary_to_notion_task:
  description: >
    Write the sumary to Notion page.
  expected_output: >
    A summary has been written into the Notion page.